#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'rspec'
require 'active_support/core_ext'
require 'colorize'

require './lib/greeting'
require './lib/hole'
require './lib/game'


puts Greeting.new

game = Game.new(ARGV)

game.scored_holes.each do |hole|
  puts "Hole #{hole.number}: #{hole.state}"
end

puts "\nHoles complete: " + "#{game.successful_holes.count} out of #{game.holes.count}"

puts "\nTotal Score: " + game.score.to_s.colorize(:green)
